on:
  release:
    types: [published]

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            eval "$(ssh-agent -s)"
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh                
            cd ~/Portfolio/webpage
            git pull 
            killall node
            npm i 
            npm run deploy > /dev/null 2>&1 & exit